apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metrics-gateway
  template:
    metadata:
      labels:
        app: metrics-gateway
    spec:
      containers:
        - name: metrics-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
