{
 "title": "Live Slurm Job Load",
 "tags": [
  "slurm",
  "hpc",
  "jobs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_id",
    "label": "SLURM Job ID",
    "query": {
     "query": "label_values(slurm_cpu_load, SLURM_JOB_ID)"
    }
   },
   {
    "name": "node",
    "label": "Slurmd Node",
    "query": {
     "query": "label_values(slurm_cpu_load{SLURM_JOB_ID=\"$job_id\"}, SLURMD_NODENAME)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live Slurm Job Load",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "slurm_cpu_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "slurm_gpu_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"}",
     "legendFormat": "GPU Load"
    },
    {
     "expr": "slurm_mem_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"}",
     "legendFormat": "Memory Load"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slurm_cpu_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slurm_gpu_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"})",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slurm_mem_load{SLURM_JOB_ID=\"$job_id\", SLURMD_NODENAME=\"$node\"})",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}